// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYFIWji4k2kekAqcwDJwazxgPwEVsJ7Z8',
    appId: '1:244946853827:web:f05bd78f98cca67de1a776',
    messagingSenderId: '244946853827',
    projectId: 'databaseforweb-cfba4',
    authDomain: 'databaseforweb-cfba4.firebaseapp.com',
    databaseURL: 'https://databaseforweb-cfba4-default-rtdb.firebaseio.com',
    storageBucket: 'databaseforweb-cfba4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtF06W8gWRG0nhyFp9TTs_g7k50rwp1T8',
    appId: '1:244946853827:android:0e8bbd6490f39534e1a776',
    messagingSenderId: '244946853827',
    projectId: 'databaseforweb-cfba4',
    databaseURL: 'https://databaseforweb-cfba4-default-rtdb.firebaseio.com',
    storageBucket: 'databaseforweb-cfba4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDrDSnRB9228xvT2s2Z-AMWd8nWysSl-o',
    appId: '1:244946853827:ios:7cf42478cf88ec43e1a776',
    messagingSenderId: '244946853827',
    projectId: 'databaseforweb-cfba4',
    databaseURL: 'https://databaseforweb-cfba4-default-rtdb.firebaseio.com',
    storageBucket: 'databaseforweb-cfba4.appspot.com',
    iosClientId: '244946853827-nd1hj3pna033v430j0rvjcgf3p8j959l.apps.googleusercontent.com',
    iosBundleId: 'com.example.jpcSecond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDrDSnRB9228xvT2s2Z-AMWd8nWysSl-o',
    appId: '1:244946853827:ios:7cf42478cf88ec43e1a776',
    messagingSenderId: '244946853827',
    projectId: 'databaseforweb-cfba4',
    databaseURL: 'https://databaseforweb-cfba4-default-rtdb.firebaseio.com',
    storageBucket: 'databaseforweb-cfba4.appspot.com',
    iosClientId: '244946853827-nd1hj3pna033v430j0rvjcgf3p8j959l.apps.googleusercontent.com',
    iosBundleId: 'com.example.jpcSecond',
  );
}
